# Generated by Django 5.2.7 on 2025-11-05 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traintype', models.CharField(max_length=100)),
                ('depratortime', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.BigIntegerField(default=2000000)),
                ('returntime', models.DateTimeField(blank=True)),
                ('capacity', models.IntegerField(default=100)),
                ('available', models.BooleanField(default=True)),
                ('rules', models.TextField(default='\n        از زمان صدور تا ساعت ۱۲ ظهر روز قبل از حرکت\n        %10 جریمه\n        از ۱۲ ظهر روز قبل تا ۳ ساعت قبل از حرکت قطار\n        %30 جریمه\n        از ۳ ساعت قبل از حرکت قطار تا لحظه حرکت\n        %50 جریمه\n        پس از حرکت قطار\n        %100 جریمه')),
                ('services', models.TextField(default='catering, train resturant available')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_destination', to='train.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_origin', to='train.city')),
            ],
            options={
                'db_table': 'train',
            },
        ),
    ]
